Interactions
drews54/Discord-Music-Bot pull request #73
Opened 2021-09-23 21:30 UTC by drews54

Uses discord-py-interactions
As Discord plans to migrate to slash-commands by April 2022, our bot should follow to the maximum possible extent. This PR is the first step in that direction.

2021-09-23 22:47 UTC, piunov1998 requested changes
I'm not racist, but Black is awful.

2021-09-23 23:27 UTC, piunov1998 commented on cogs/music.py
> +        )
Зачем?

2021-09-24 08:54 UTC, drews54 commented on cogs/music.py
> +        )
Чтобы в случае false функция вернула false, а не непонятно что.
P.S. Я осознал, что это можно было сделать ещё проще… вернусь домой – сделаю.

2021-09-24 13:54 UTC, piunov1998 commented on cogs/music.py
> +        )
она и так возвращает False

2021-09-24 13:56 UTC, piunov1998 commented on cogs/music.py
> +        )
Вернее None, что равносильно в данном случае False

2021-09-24 13:58 UTC, piunov1998 commented on cogs/music.py
> +        )
Но лучшим образом будет сделать:
`return re.fullmatch(r"https?://(www\.)?youtu(\.be|be\.com)/[\S]+", url)`

2021-09-24 13:58 UTC, drews54 commented on cogs/music.py
> +        )
> Вернее None, что равносильно в данном случае False

Ты настолько неправ, что даже объяснять не хочется...

2021-09-26 10:58 UTC, closed without merging